/**
 * Forked Futures — canonical type contract.
 *
 * These types are the single source of truth shared by the mock dataset,
 * the zustand store, every page, and the Zod schemas (lib/schemas.ts mirrors
 * this file at runtime). Responsible-AI primitives — claim provenance and
 * qualitative uncertainty levels — are first-class here so they cannot be
 * dropped by any downstream consumer.
 */

export type Level = "low" | "medium" | "high";

export type ClaimType = "user_provided" | "source_supported" | "ai_inferred";

export type Urgency = "exploring" | "soon" | "deciding_now";

export type SourceType =
  | "curated_research"
  | "framework"
  | "labor_market"
  | "user_provided"
  | "ai_inferred";

/** Raw decision context captured on the Intake page. */
export interface UserContext {
  decision: string;
  options: string[];
  major: string;
  skills: string[];
  values: string[];
  constraints: string[];
  fears: string[];
  background: string;
  timeHorizon: string;
  urgency: Urgency;
}

/** An AI-generated clarifying question, optionally answered by the user. */
export interface ClarifyingQuestion {
  id: string;
  question: string;
  why: string;
  /** What the question is trying to disambiguate (shown subtly in UI). */
  probes: string;
  answer?: string;
}

/** A unit of curated/keyword-retrieved evidence backing a branch. */
export interface EvidenceCard {
  id: string;
  title: string;
  category: string;
  content: string;
  sourceType: SourceType;
  /** Short note on which reasoning step this card was used for. */
  usedFor: string;
  evidenceStrength: Level;
}

/** A base-rate framing signal — never an individual prediction. */
export interface BaseRateSignal {
  claim: string;
  source: string;
  /** "occupation-level" | "field-level" | "framework-level" etc. */
  coverageLevel: string;
  confidence: Level;
  limitations: string;
}

/** A single tracked assumption with explicit provenance + a way to test it. */
export interface Assumption {
  claim: string;
  type: ClaimType;
  confidence: Level;
  howToTest: string;
}

/** One step on a 12-month trajectory. */
export interface TimelineItem {
  time: string;
  description: string;
  uncertaintyNote: string;
}

export type RegretType =
  | "action"
  | "inaction"
  | "identity"
  | "financial"
  | "relational"
  | "opportunity";

export interface RegretRadarItem {
  regretType: RegretType;
  level: Level;
  description: string;
}

export interface ExperimentStep {
  day: number;
  action: string;
  purpose: string;
}

/** Qualitative calibration — no fake precise probabilities. */
export interface CalibrationResult {
  evidenceStrength: Level;
  userFit: Level;
  constraintRisk: Level;
  uncertaintyLevel: Level;
  dataCoverageNote: string;
}

/** A single plausible future branch (the system always emits exactly three). */
export interface FutureBranch {
  id: string;
  /** Short track label used for the map node, e.g. "Quant Signal Track". */
  track: string;
  title: string;
  thesis: string;
  baseRateSignals: BaseRateSignal[];
  evidenceCards: EvidenceCard[];
  twelveMonthTrajectory: TimelineItem[];
  hiddenTradeoffs: string[];
  opportunityCosts: string[];
  reversibility: Level;
  skillCompounding: string;
  emotionalLoad: string;
  bottlenecks: string[];
  assumptions: Assumption[];
  premortem: string[];
  regretRadar: RegretRadarItem[];
  sevenDayExperiment: ExperimentStep[];
  killCriteria: string[];
  calibration: CalibrationResult;
}

export interface DecisionBrief {
  decisionFrame: string;
  strongestSignals: string[];
  biggestUncertainties: string[];
  whatAIWillNotDecide: string[];
  recommendedExperiments: string[];
  humanInLoopStatement: string;
  responsibleAIStatement: string;
}

/** A single Future Self chat turn, grounded in a branch. */
export interface ChatMessage {
  role: "user" | "assistant";
  content: string;
}

/** The full simulation payload returned by /api/simulate. */
export interface SimulationResult {
  context: UserContext;
  branches: FutureBranch[];
  /** True when generated by mock fallback rather than a live model. */
  mocked: boolean;
  generatedNote: string;
}

/** Convenience labels for level/claim enums used across the UI. */
export const LEVEL_LABELS: Record<Level, string> = {
  low: "Low",
  medium: "Medium",
  high: "High",
};

export const CLAIM_LABELS: Record<ClaimType, string> = {
  user_provided: "You told us",
  source_supported: "Source-supported",
  ai_inferred: "AI-inferred",
};

export const URGENCY_LABELS: Record<Urgency, string> = {
  exploring: "Just exploring",
  soon: "Deciding soon",
  deciding_now: "Deciding now",
};
